version: "3"
name: resume-builder

services:
  # Fast Api Backend
  resume-bulder-fastapi_backend:
    build: ./FastApiBackend
    image: resume-bulder-fastapi_backend
    container_name: resume-bulder-fastapi_backend
    restart: unless-stopped
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./FastApiBackend:/FastApiBackend/
    depends_on:
      - resume_builder_db
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 5000

  vue_frontend:
    build:
      context: ./VueFrontend
    image: vuefrontend
    container_name: vue_frontend
    restart: unless-stopped
    ports:
      - 5173:5173
      - 24678:24678
    tty: true
    volumes:
      - ./VueFrontend:/app
    depends_on:
      - resume-bulder-fastapi_backend
      - resume_builder_db

  resume_builder_db:
    image: postgres:15.3-alpine3.18
    container_name: resume_builder_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - resume-builder-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  resume-builder-postgres-data:
